"""feat: in118

Revision ID: 24a3459f351e
Revises: f45e0fc507d6
Create Date: 2026-03-17 13:04:17.788743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a3459f351e'
down_revision: Union[str, None] = 'f45e0fc507d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Ajouter la colonne en tant que nullable d'abord
    op.add_column('tutorials', sa.Column('lang', sa.String(length=5), nullable=True))
    
    # 2. Mettre à jour les lignes existantes avec 'fr'
    op.execute("UPDATE tutorials SET lang = 'fr' WHERE lang IS NULL")
    
    # 3. Rendre la colonne NOT NULL
    op.alter_column('tutorials', 'lang', nullable=False)
    
    op.create_index(op.f('ix_tutorials_lang'), 'tutorials', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorials_lang'), table_name='tutorials')
    op.drop_column('tutorials', 'lang')
    # ### end Alembic commands ###
