"""feat: tags, featured, views_count on tutorials

Revision ID: 44907de619b2
Revises: 5dd2bbdef421
Create Date: 2026-03-22 14:54:37.499042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44907de619b2'
down_revision: Union[str, None] = '5dd2bbdef421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorials', sa.Column('tags', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('tutorials', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tutorials', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorials', 'views_count')
    op.drop_column('tutorials', 'is_featured')
    op.drop_column('tutorials', 'tags')
    # ### end Alembic commands ###
