"""feat: in118

Revision ID: a13dd38bead7
Revises: 24a3459f351e
Create Date: 2026-03-21 07:55:56.402432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13dd38bead7'
down_revision: Union[str, None] = '24a3459f351e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokens_retention_days', sa.Integer(), nullable=False),
    sa.Column('visits_retention_days', sa.Integer(), nullable=False),
    sa.Column('logs_retention_days', sa.Integer(), nullable=False),
    sa.Column('cleanup_frequency', sa.String(), nullable=False),
    sa.Column('last_cleanup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_settings')
    # ### end Alembic commands ###
